
apiVersion: batch/v1
kind: Job
metadata:
  name: check2
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: gate
        image: zachboyofdestiny/snoopdb:gate
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: K8S_JOB
          value: "true"
