apiVersion: batch/v1
kind: Job
metadata:
  name: snoop-gate
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: snoopdb
        image: zachboyofdestiny/snoopdb:2020-09-03
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: K8S_JOB
          value: "true"
      restartPolicy: Never
